version: '3.8'

services:
  ai-agent-backend:
    build: .
    container_name: ai-agent-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-agent-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: ai-agent-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-agent-backend
    networks:
      - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge

volumes:
  logs:
    driver: local
